apiVersion: batch/v1
kind: Job
metadata:
  name: client-load-test
spec:
  completions: ${NUM_CLIENTES}
  parallelism: ${NUM_CLIENTES}
  completionMode: Indexed
  template:
    spec:
      containers:
        - name: client
          image: meu-cliente:latest
          imagePullPolicy: Never
          env:
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
            - name: NUM_MENSAGENS
              value: "${NUM_MENSAGENS}"
            - name: SERVER_HOST
              value: "${SERVER_SERVICE}"
          command: ["python", "app.py"]
          # Resources removed to allow unlimited usage of available system resources
          # This will improve performance by removing CPU and memory bottlenecks
      restartPolicy: Never
