apiVersion: batch/v1
kind: Job
metadata:
  name: client-load-test
spec:
  completions: ${NUM_CLIENTES}
  parallelism: ${NUM_CLIENTES}
  completionMode: Indexed
  template:
    spec:
      containers:
        - name: client
          image: meu-cliente
          imagePullPolicy: IfNotPresent
          env:
            - name: JOB_COMPLETION_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
            - name: NUM_MENSAGENS
              value: "${NUM_MENSAGENS}"
            - name: SERVER_SERVICE
              value: "${SERVER_SERVICE}"
          command:
            [
              "sh",
              "-c",
              "python app.py ${JOB_COMPLETION_INDEX} ${NUM_MENSAGENS}",
            ]
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
      restartPolicy: Never
