kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Control plane node otimizado
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        maxPods: 500
        cpuManagerPolicy: "none"
        systemReserved:
          cpu: "200m"
          memory: "512Mi"
  # Worker node 1
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        maxPods: 500
        cpuManagerPolicy: "none"
        systemReserved:
          cpu: "200m"
          memory: "512Mi"
  # Worker node 2
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        maxPods: 500
        cpuManagerPolicy: "none"
        systemReserved:
          cpu: "200m"
          memory: "512Mi"
          cpu: "500m"
          memory: "1Gi"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        maxPods: 300
        cpuManagerPolicy: "static"
        systemReserved:
          cpu: "500m"
          memory: "1Gi"
