apiVersion: batch/v1
kind: Job
metadata:
  name: test-simple
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: client
          image: meu-cliente:latest
          imagePullPolicy: Never
          env:
            - name: JOB_COMPLETION_INDEX
              value: "0"
            - name: NUM_MENSAGENS
              value: "10"
            - name: SERVER_HOST
              value: "server-service-go"
          command: ["python", "app.py"]
      restartPolicy: Never
