apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-deployment-python
  template:
    metadata:
      labels:
        app: server-deployment-python
    spec:
      containers:
        - name: server
          volumeMounts:
            - name: data-volume
              mountPath: /data
          image: meu-servidor-python
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          # Resources removed to allow unlimited usage of available system resources
          # This will improve performance by removing CPU and memory bottlenecks
      volumes:
        - name: data-volume
          emptyDir: {} # Each pod gets its own storage
